name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libwebsockets-dev
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y libcjson-dev
    - name: make
      run: make release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "qr_login_linux"
        path: "./qr_login"
        
            
